### PR TITLE
Brenda

### PR DESCRIPTION
**Pull request by Brendathiaini**
Check whether there's sth I need to change, in the login and sign up pages

### CODE REVIEW

**Comment by NerdNestKE** [comment]
Checked

**Comment by NerdNestKE** [comment]
Waiting for reviews from you guys

**Review by lumasia07 — APPROVED** [review]
Nice work Brenda, your first Hello World using Github Actions.

**Comment by Nixonu-i** [comment]
I think it's great

**Review by Nixonu-i — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by marube2005** [comment]
Nice work done Brenda

**Review by marube2005 — APPROVED** [review]
Nice work done Brenda

**Review by PAULTYLER192 — APPROVED** [review]
Bravo that's the spirit Brenda

**Pull request merged**
