### PR TITLE
Changed README

### PR DESCRIPTION
**Pull request by NerdNestKE**

### CODE REVIEW

**Comment by Nixonu-i** [comment]
viewed

**Comment by marube2005** [comment]
Approved

**Comment by ghost** [comment]
noted

**Comment by marube2005** [comment]
Approved

**Review by ghost — APPROVED** [review]

**Comment by marube2005** [comment]
Approved

**Review by Nixonu-i — APPROVED** [review]

**Comment by marube2005** [comment]
Noted

**Review by PAULTYLER192 — APPROVED** [review]

**Pull request merged**
